version: "3.5"

services:

  k3d:
    image: rancher/k3s:v1.17.2-k3s1
    container_name: ksfs-k3d
    hostname: k3d
    privileged: true
    command:
      - server
      - --https-listen-port
      - "6443"
      - --no-deploy
      - traefik
    environment:
      K3D_PORT: ${K3D_PORT:-6443}
    ports:
    - "${K3D_PORT:-6443}:6443"
    volumes:
    - ./k3d.resolv.conf:/etc/resolv.conf:ro
    - kube-sa:/var/run/secrets/kubernetes.io/serviceaccount

  dotnet:
    build:
      context: ../../
      dockerfile: cicd/sdk/Dockerfile
    container_name: ksfs-dotnet
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    working_dir: /app
    command:
      - sh
      - -c
      - |
        mkdir -p /mnt/ksfs /mnt/redir
        dotnet watch run -- /mnt/ksfs /mnt/redir
    volumes:
    - ../../KubeSecretFS.csproj:/app/KubeSecretFS.csproj
    - ../../src:/app/src
    - kube-sa:/var/run/secrets/kubernetes.io/serviceaccount:ro

volumes:
  kube-sa: {}
