---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: default
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io
