---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-secret-fs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-secret-fs
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-secret-fs
subjects:
  - kind: ServiceAccount
    name: kube-secret-fs
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io
