name: release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test
        run: ./cicd/test/test.sh
        env:
          CI_RELEASE: "true"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to DockerHub
        run: |
          branch="${GITHUB_REF#refs/heads/}"
          tag="${GITHUB_REF#refs/tags/v}"

          if [ "$branch" != "$GITHUB_REF" ]; then

            branch="$(echo "$branch" | sed -e 's/[^a-zA-Z0-9\-\.]/-/g')"
            docker tag "ksfs_dotnet" "boxboat/kube-secret-fs:commit-${branch}"
            docker push "boxboat/kube-secret-fs:commit-${branch}"

          elif [ "$tag" != "$GITHUB_REF" ]; then

            tag="$(echo "$tag" | sed -e 's/[^a-zA-Z0-9\-\.]/-/g')"
            docker tag "ksfs_dotnet" "boxboat/kube-secret-fs:${tag}"
            docker push "boxboat/kube-secret-fs:${tag}"

            if ! echo "$tag" | grep -qF '-'; then
              docker tag "ksfs_dotnet" "boxboat/kube-secret-fs:latest"
              docker push "boxboat/kube-secret-fs:latest"
            fi

          else
            echo "unable to determine tag" >&2
            exit 1
          fi
